/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author asus pc
 */
public class VistaCliente extends javax.swing.JFrame {

    private static VistaCliente ventana = new VistaCliente();

    public VistaCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelAdministrador = new javax.swing.JLabel();
        jLabelClientes = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jPanelSeleccion = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelDni = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jTextFieldMail = new javax.swing.JTextField();
        jTextFieldPasaporte = new javax.swing.JTextField();
        jTextFieldTarjeta = new javax.swing.JTextField();
        jLabePasaporte = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        jLabelTarjeta = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelFondo.setBackground(new java.awt.Color(153, 204, 51));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInicio.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(102, 153, 51));
        jLabelInicio.setText("Inicio //");
        jLabelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInicioMouseClicked(evt);
            }
        });
        jPanelFondo.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 20, 98, 30));

        jLabelAdministrador.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabelAdministrador.setForeground(new java.awt.Color(102, 153, 51));
        jLabelAdministrador.setText("Administrador /");
        jLabelAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdministradorMouseClicked(evt);
            }
        });
        jPanelFondo.add(jLabelAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 20, -1, 30));

        jLabelClientes.setBackground(new java.awt.Color(102, 153, 51));
        jLabelClientes.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabelClientes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClientes.setText("Clientes");
        jPanelFondo.add(jLabelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 30));

        jLabelCerrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(102, 153, 51));
        jLabelCerrar.setText("X");
        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        jPanelFondo.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 15, 15));

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "DNI", "Mail", "Pasaporte", "Nro Tarjeta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setToolTipText("");
        jTableClientes.setSelectionBackground(new java.awt.Color(102, 153, 51));
        jTableClientes.getTableHeader().setReorderingAllowed(false);
        jScrollPaneClientes.setViewportView(jTableClientes);

        jPanelFondo.add(jScrollPaneClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 75, 691, 240));

        jPanelSeleccion.setBackground(new java.awt.Color(102, 153, 51));
        jPanelSeleccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanelSeleccion.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 44, 228, 31));

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldApellido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanelSeleccion.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 44, 228, 31));

        jLabelDni.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelDni.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDni.setText("DNI");
        jPanelSeleccion.add(jLabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 20, -1, -1));

        jLabelApellido.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido");
        jPanelSeleccion.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 20, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre");
        jPanelSeleccion.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 20, -1, -1));

        jTextFieldDni.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldDni.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanelSeleccion.add(jTextFieldDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 44, 105, 31));

        jTextFieldMail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldMail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanelSeleccion.add(jTextFieldMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 114, 228, 31));

        jTextFieldPasaporte.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldPasaporte.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanelSeleccion.add(jTextFieldPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 114, 170, 31));

        jTextFieldTarjeta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldTarjeta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanelSeleccion.add(jTextFieldTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 114, 165, 31));

        jLabePasaporte.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabePasaporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabePasaporte.setText("N° Pasaporte");
        jPanelSeleccion.add(jLabePasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 90, -1, -1));

        jLabelMail.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMail.setText("Mail");
        jPanelSeleccion.add(jLabelMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 90, -1, -1));

        jLabelTarjeta.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTarjeta.setText("N° Tarjeta");
        jPanelSeleccion.add(jLabelTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 90, -1, -1));

        jPanelFondo.add(jPanelSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 341, 691, 170));

        jButtonEliminar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("- Eliminar cliente");
        jButtonEliminar.setBorder(null);
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFondo.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 530, 168, 31));

        jButtonModificar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonModificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("/ Modificar cliente");
        jButtonModificar.setBorder(null);
        jButtonModificar.setBorderPainted(false);
        jButtonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFondo.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 168, 31));

        jButtonAgregar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("+ Agregar cliente");
        jButtonAgregar.setBorder(null);
        jButtonAgregar.setBorderPainted(false);
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFondo.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 530, 168, 31));

        jButtonBuscar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("ó Buscar cliente");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelFondo.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 530, 168, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMouseClicked
        ventana.setVisible(false);
        VistaPrincipal.visibilidad(true);
    }//GEN-LAST:event_jLabelInicioMouseClicked

    private void jLabelAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdministradorMouseClicked
        ventana.setVisible(false);
        VistaAdmin.visibilidad(true);
    }//GEN-LAST:event_jLabelAdministradorMouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    public static void visibilidad(boolean estado) {
        ventana.setVisible(estado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabePasaporte;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTarjeta;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelSeleccion;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPasaporte;
    private javax.swing.JTextField jTextFieldTarjeta;
    // End of variables declaration//GEN-END:variables
}
