/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Asiento;
import clases.Ciudad;
import clases.Vuelo;
import clasesData.AsientoData;
import clasesData.CiudadData;
import clasesData.VueloData;
import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author asus pc
 */
public class VistaVuelos extends javax.swing.JFrame {

    private VueloData vD = new VueloData();
    private CiudadData cD = new CiudadData();
    private AsientoData aD = new AsientoData();
    private DefaultTableModel modelo;
    private static VistaVuelos ventana = new VistaVuelos();

    public VistaVuelos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.llenarTabla();
        this.llenarComboCiudades();
        jPanelAsientos.setVisible(false);
        jPanelFondoAsientos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        jPanelAsientos = new javax.swing.JPanel();
        jButtonV001 = new javax.swing.JButton();
        jButtonP002 = new javax.swing.JButton();
        jButtonP003 = new javax.swing.JButton();
        jButtonV004 = new javax.swing.JButton();
        jButtonV005 = new javax.swing.JButton();
        jButtonP006 = new javax.swing.JButton();
        jButtonP007 = new javax.swing.JButton();
        jButtonV008 = new javax.swing.JButton();
        jButtonV009 = new javax.swing.JButton();
        jButtonP010 = new javax.swing.JButton();
        jButtonP011 = new javax.swing.JButton();
        jButtonV012 = new javax.swing.JButton();
        jButtonV013 = new javax.swing.JButton();
        jButtonP014 = new javax.swing.JButton();
        jButtonP015 = new javax.swing.JButton();
        jButtonV016 = new javax.swing.JButton();
        jButtonV017 = new javax.swing.JButton();
        jButtonP018 = new javax.swing.JButton();
        jButtonP019 = new javax.swing.JButton();
        jButtonV020 = new javax.swing.JButton();
        jButtonV021 = new javax.swing.JButton();
        jButtonP022 = new javax.swing.JButton();
        jButtonP023 = new javax.swing.JButton();
        jButtonV024 = new javax.swing.JButton();
        jButtonV025 = new javax.swing.JButton();
        jButtonP026 = new javax.swing.JButton();
        jButtonP027 = new javax.swing.JButton();
        jButtonV028 = new javax.swing.JButton();
        jButtonV029 = new javax.swing.JButton();
        jButtonP030 = new javax.swing.JButton();
        jButtonP031 = new javax.swing.JButton();
        jButtonV032 = new javax.swing.JButton();
        jPanelFondoAsientos = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelAdministrador = new javax.swing.JLabel();
        jLabelVuelos = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jButtonDisponibles = new javax.swing.JButton();
        jButtonLimpiarFiltros = new javax.swing.JButton();
        jButtonAsientos = new javax.swing.JButton();
        jScrollPaneVuelos = new javax.swing.JScrollPane();
        jTableVuelos = new javax.swing.JTable();
        jPanelFondoSeleccion = new javax.swing.JPanel();
        jLabelSalida = new javax.swing.JLabel();
        jDateChooserArribo = new com.toedter.calendar.JDateChooser();
        jComboBoxAerolinea = new javax.swing.JComboBox<>();
        jComboBoxAeronave = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jLabelAerolinea = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jDateChooserSalida = new com.toedter.calendar.JDateChooser();
        jLabelOrigen = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelAsiento = new javax.swing.JLabel();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jLabelArribo = new javax.swing.JLabel();
        jLabelAeronave = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 204, 0));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        JPanel.setBackground(new java.awt.Color(153, 204, 51));
        JPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAsientos.setBackground(new java.awt.Color(102, 153, 51));
        jPanelAsientos.setInheritsPopupMenu(true);

        jButtonV001.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV001.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV001.setText("V001");
        jButtonV001.setBorder(null);
        jButtonV001.setBorderPainted(false);
        jButtonV001.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV001ActionPerformed(evt);
            }
        });

        jButtonP002.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP002.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP002.setText("P002");
        jButtonP002.setToolTipText("");
        jButtonP002.setBorder(null);
        jButtonP002.setBorderPainted(false);
        jButtonP002.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP002ActionPerformed(evt);
            }
        });

        jButtonP003.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP003.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP003.setText("V004");
        jButtonP003.setToolTipText("");
        jButtonP003.setBorder(null);
        jButtonP003.setBorderPainted(false);
        jButtonP003.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP003ActionPerformed(evt);
            }
        });

        jButtonV004.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV004.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV004.setText("P003");
        jButtonV004.setBorder(null);
        jButtonV004.setBorderPainted(false);
        jButtonV004.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV004ActionPerformed(evt);
            }
        });

        jButtonV005.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV005.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV005.setText("V005");
        jButtonV005.setBorder(null);
        jButtonV005.setBorderPainted(false);
        jButtonV005.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV005ActionPerformed(evt);
            }
        });

        jButtonP006.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP006.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP006.setText("P006");
        jButtonP006.setToolTipText("");
        jButtonP006.setBorder(null);
        jButtonP006.setBorderPainted(false);
        jButtonP006.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP006.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP006ActionPerformed(evt);
            }
        });

        jButtonP007.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP007.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP007.setText("P007");
        jButtonP007.setBorder(null);
        jButtonP007.setBorderPainted(false);
        jButtonP007.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP007.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP007ActionPerformed(evt);
            }
        });

        jButtonV008.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV008.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV008.setText("V008");
        jButtonV008.setToolTipText("");
        jButtonV008.setBorder(null);
        jButtonV008.setBorderPainted(false);
        jButtonV008.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV008.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV008ActionPerformed(evt);
            }
        });

        jButtonV009.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV009.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV009.setText("V009");
        jButtonV009.setBorder(null);
        jButtonV009.setBorderPainted(false);
        jButtonV009.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV009.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV009ActionPerformed(evt);
            }
        });

        jButtonP010.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP010.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP010.setText("P010");
        jButtonP010.setToolTipText("");
        jButtonP010.setBorder(null);
        jButtonP010.setBorderPainted(false);
        jButtonP010.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP010.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP010ActionPerformed(evt);
            }
        });

        jButtonP011.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP011.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP011.setText("P011");
        jButtonP011.setBorder(null);
        jButtonP011.setBorderPainted(false);
        jButtonP011.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP011.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP011ActionPerformed(evt);
            }
        });

        jButtonV012.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV012.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV012.setText("V012");
        jButtonV012.setToolTipText("");
        jButtonV012.setBorder(null);
        jButtonV012.setBorderPainted(false);
        jButtonV012.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV012.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV012ActionPerformed(evt);
            }
        });

        jButtonV013.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV013.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV013.setText("V013");
        jButtonV013.setBorder(null);
        jButtonV013.setBorderPainted(false);
        jButtonV013.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV013.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV013ActionPerformed(evt);
            }
        });

        jButtonP014.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP014.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP014.setText("P014");
        jButtonP014.setToolTipText("");
        jButtonP014.setBorder(null);
        jButtonP014.setBorderPainted(false);
        jButtonP014.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP014.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP014ActionPerformed(evt);
            }
        });

        jButtonP015.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP015.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP015.setText("P015");
        jButtonP015.setBorder(null);
        jButtonP015.setBorderPainted(false);
        jButtonP015.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP015.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP015ActionPerformed(evt);
            }
        });

        jButtonV016.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV016.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV016.setText("V016");
        jButtonV016.setToolTipText("");
        jButtonV016.setBorder(null);
        jButtonV016.setBorderPainted(false);
        jButtonV016.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV016.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV016ActionPerformed(evt);
            }
        });

        jButtonV017.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV017.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV017.setText("V017");
        jButtonV017.setBorder(null);
        jButtonV017.setBorderPainted(false);
        jButtonV017.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV017ActionPerformed(evt);
            }
        });

        jButtonP018.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP018.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP018.setText("P018");
        jButtonP018.setToolTipText("");
        jButtonP018.setBorder(null);
        jButtonP018.setBorderPainted(false);
        jButtonP018.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP018ActionPerformed(evt);
            }
        });

        jButtonP019.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP019.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP019.setText("P019");
        jButtonP019.setBorder(null);
        jButtonP019.setBorderPainted(false);
        jButtonP019.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP019ActionPerformed(evt);
            }
        });

        jButtonV020.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV020.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV020.setText("V020");
        jButtonV020.setToolTipText("");
        jButtonV020.setBorder(null);
        jButtonV020.setBorderPainted(false);
        jButtonV020.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV020ActionPerformed(evt);
            }
        });

        jButtonV021.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV021.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV021.setText("V021");
        jButtonV021.setBorder(null);
        jButtonV021.setBorderPainted(false);
        jButtonV021.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV021.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV021ActionPerformed(evt);
            }
        });

        jButtonP022.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP022.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP022.setText("P022");
        jButtonP022.setToolTipText("");
        jButtonP022.setBorder(null);
        jButtonP022.setBorderPainted(false);
        jButtonP022.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP022.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP022ActionPerformed(evt);
            }
        });

        jButtonP023.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP023.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP023.setText("P023");
        jButtonP023.setBorder(null);
        jButtonP023.setBorderPainted(false);
        jButtonP023.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP023.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP023ActionPerformed(evt);
            }
        });

        jButtonV024.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV024.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV024.setText("V024");
        jButtonV024.setToolTipText("");
        jButtonV024.setBorder(null);
        jButtonV024.setBorderPainted(false);
        jButtonV024.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV024ActionPerformed(evt);
            }
        });

        jButtonV025.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV025.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV025.setText("V025");
        jButtonV025.setBorder(null);
        jButtonV025.setBorderPainted(false);
        jButtonV025.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV025.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV025ActionPerformed(evt);
            }
        });

        jButtonP026.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP026.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP026.setText("P026");
        jButtonP026.setToolTipText("");
        jButtonP026.setBorder(null);
        jButtonP026.setBorderPainted(false);
        jButtonP026.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP026.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP026ActionPerformed(evt);
            }
        });

        jButtonP027.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP027.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP027.setText("P027");
        jButtonP027.setBorder(null);
        jButtonP027.setBorderPainted(false);
        jButtonP027.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP027.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP027ActionPerformed(evt);
            }
        });

        jButtonV028.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV028.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV028.setText("V028");
        jButtonV028.setToolTipText("");
        jButtonV028.setBorder(null);
        jButtonV028.setBorderPainted(false);
        jButtonV028.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV028.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV028ActionPerformed(evt);
            }
        });

        jButtonV029.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV029.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV029.setText("V029");
        jButtonV029.setBorder(null);
        jButtonV029.setBorderPainted(false);
        jButtonV029.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV029.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV029ActionPerformed(evt);
            }
        });

        jButtonP030.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP030.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP030.setText("P030");
        jButtonP030.setToolTipText("");
        jButtonP030.setBorder(null);
        jButtonP030.setBorderPainted(false);
        jButtonP030.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP030.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP030ActionPerformed(evt);
            }
        });

        jButtonP031.setBackground(new java.awt.Color(153, 204, 51));
        jButtonP031.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonP031.setText("P031");
        jButtonP031.setBorder(null);
        jButtonP031.setBorderPainted(false);
        jButtonP031.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonP031.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonP031ActionPerformed(evt);
            }
        });

        jButtonV032.setBackground(new java.awt.Color(153, 204, 51));
        jButtonV032.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonV032.setText("V032");
        jButtonV032.setToolTipText("");
        jButtonV032.setBorder(null);
        jButtonV032.setBorderPainted(false);
        jButtonV032.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonV032.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonV032ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAsientosLayout = new javax.swing.GroupLayout(jPanelAsientos);
        jPanelAsientos.setLayout(jPanelAsientosLayout);
        jPanelAsientosLayout.setHorizontalGroup(
            jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAsientosLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAsientosLayout.createSequentialGroup()
                        .addComponent(jButtonV029, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP030, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonP031, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonV032, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAsientosLayout.createSequentialGroup()
                        .addComponent(jButtonV025, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP026, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonP027, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonV028, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAsientosLayout.createSequentialGroup()
                        .addComponent(jButtonV021, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP022, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonP023, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonV024, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAsientosLayout.createSequentialGroup()
                        .addComponent(jButtonV017, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP018, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonP019, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonV020, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAsientosLayout.createSequentialGroup()
                        .addComponent(jButtonV013, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP014, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonP015, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonV016, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAsientosLayout.createSequentialGroup()
                        .addComponent(jButtonV009, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP010, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonP011, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonV012, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAsientosLayout.createSequentialGroup()
                        .addComponent(jButtonV005, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP006, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonP007, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonV008, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAsientosLayout.createSequentialGroup()
                        .addComponent(jButtonV001, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP002, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonV004, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonP003, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanelAsientosLayout.setVerticalGroup(
            jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAsientosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonV004, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP003, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV001, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP002, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP007, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV008, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV005, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP006, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP011, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV012, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV009, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP010, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP015, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV016, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV013, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP014, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP019, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV020, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV017, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP018, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP023, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV024, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV021, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP022, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP027, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV028, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV025, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP026, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonP031, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV032, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV029, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP030, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel.add(jPanelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 100, 162, 248));

        jPanelFondoAsientos.setOpaque(false);
        jPanelFondoAsientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelFondoAsientosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoAsientosLayout = new javax.swing.GroupLayout(jPanelFondoAsientos);
        jPanelFondoAsientos.setLayout(jPanelFondoAsientosLayout);
        jPanelFondoAsientosLayout.setHorizontalGroup(
            jPanelFondoAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        jPanelFondoAsientosLayout.setVerticalGroup(
            jPanelFondoAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );

        JPanel.add(jPanelFondoAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 756, 645));

        jLabelInicio.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(102, 153, 51));
        jLabelInicio.setText("Inicio //");
        jLabelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInicioMouseClicked(evt);
            }
        });
        JPanel.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 20, 98, 30));

        jLabelAdministrador.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabelAdministrador.setForeground(new java.awt.Color(102, 153, 51));
        jLabelAdministrador.setText("Administrador /");
        jLabelAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAdministradorMouseClicked(evt);
            }
        });
        JPanel.add(jLabelAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 20, -1, 30));

        jLabelVuelos.setBackground(new java.awt.Color(102, 153, 51));
        jLabelVuelos.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabelVuelos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVuelos.setText("Vuelos");
        JPanel.add(jLabelVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 30));

        jLabelCerrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(102, 153, 51));
        jLabelCerrar.setText("X");
        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        JPanel.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 15, 15));

        jButtonDisponibles.setBackground(new java.awt.Color(102, 153, 51));
        jButtonDisponibles.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDisponibles.setText("Vuelos disponibles");
        jButtonDisponibles.setToolTipText("");
        jButtonDisponibles.setBorder(null);
        jButtonDisponibles.setBorderPainted(false);
        jButtonDisponibles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisponiblesActionPerformed(evt);
            }
        });
        JPanel.add(jButtonDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 160, 31));

        jButtonLimpiarFiltros.setBackground(new java.awt.Color(102, 153, 51));
        jButtonLimpiarFiltros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonLimpiarFiltros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiarFiltros.setText("Limpiar filtros");
        jButtonLimpiarFiltros.setToolTipText("");
        jButtonLimpiarFiltros.setBorder(null);
        jButtonLimpiarFiltros.setBorderPainted(false);
        jButtonLimpiarFiltros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarFiltrosActionPerformed(evt);
            }
        });
        JPanel.add(jButtonLimpiarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 120, 31));

        jButtonAsientos.setBackground(new java.awt.Color(102, 153, 51));
        jButtonAsientos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAsientos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAsientos.setText("Asientos");
        jButtonAsientos.setToolTipText("");
        jButtonAsientos.setBorder(null);
        jButtonAsientos.setBorderPainted(false);
        jButtonAsientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAsientos.setEnabled(false);
        jButtonAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsientosActionPerformed(evt);
            }
        });
        JPanel.add(jButtonAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 70, 91, 31));

        jTableVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Aerolinea", "Aeronave", "Origen", "Destino", "Salida", "Arribo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVuelos.setToolTipText("");
        jTableVuelos.setSelectionBackground(new java.awt.Color(102, 153, 51));
        jTableVuelos.getTableHeader().setReorderingAllowed(false);
        jTableVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVuelosMouseClicked(evt);
            }
        });
        jScrollPaneVuelos.setViewportView(jTableVuelos);
        if (jTableVuelos.getColumnModel().getColumnCount() > 0) {
            jTableVuelos.getColumnModel().getColumn(0).setResizable(false);
            jTableVuelos.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableVuelos.getColumnModel().getColumn(1).setResizable(false);
            jTableVuelos.getColumnModel().getColumn(2).setResizable(false);
            jTableVuelos.getColumnModel().getColumn(3).setResizable(false);
            jTableVuelos.getColumnModel().getColumn(4).setResizable(false);
            jTableVuelos.getColumnModel().getColumn(5).setResizable(false);
            jTableVuelos.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableVuelos.getColumnModel().getColumn(6).setResizable(false);
            jTableVuelos.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableVuelos.getColumnModel().getColumn(7).setResizable(false);
            jTableVuelos.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        JPanel.add(jScrollPaneVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 105, 691, 245));

        jPanelFondoSeleccion.setBackground(new java.awt.Color(102, 153, 51));

        jLabelSalida.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelSalida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalida.setText("Salida");

        jDateChooserArribo.setBackground(new java.awt.Color(102, 153, 51));
        jDateChooserArribo.setDateFormatString("dd/MM/yyyy HH:mm");

        jComboBoxAerolinea.setBackground(new java.awt.Color(102, 153, 51));
        jComboBoxAerolinea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una aerolinea", "Aerolineas Argentinas", "FlyBondi", "Emirates", "LATAM", "LAN" }));

        jComboBoxAeronave.setBackground(new java.awt.Color(102, 153, 51));
        jComboBoxAeronave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una aeronave", "Boeing 747", "Boeing 757", "Boeing 767", "Airbus A330", "Airbus A340", "Airbus A350" }));

        jComboBoxDestino.setBackground(new java.awt.Color(102, 153, 51));
        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDestino.setBorder(null);

        jComboBoxEstado.setBackground(new java.awt.Color(102, 153, 51));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "n", "d", "c" }));

        jLabelAerolinea.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelAerolinea.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAerolinea.setText("Aerolinea");

        jLabelEstado.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado.setText("Estado");

        jDateChooserSalida.setBackground(new java.awt.Color(102, 153, 51));
        jDateChooserSalida.setDateFormatString("dd/MM/yyyy HH:mm");

        jLabelOrigen.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelOrigen.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrigen.setText("Ciudad de Origen");

        jLabelDestino.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDestino.setText("Ciudad de Destino");

        jLabelAsiento.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelAsiento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAsiento.setText("Precio");

        jComboBoxOrigen.setBackground(new java.awt.Color(102, 153, 51));
        jComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOrigen.setBorder(null);

        jLabelArribo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelArribo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArribo.setText("Arribo");

        jLabelAeronave.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelAeronave.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAeronave.setText("Aeronave");

        jTextFieldPrecio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jTextFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoSeleccionLayout = new javax.swing.GroupLayout(jPanelFondoSeleccion);
        jPanelFondoSeleccion.setLayout(jPanelFondoSeleccionLayout);
        jPanelFondoSeleccionLayout.setHorizontalGroup(
            jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addComponent(jComboBoxAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jComboBoxAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addComponent(jLabelOrigen)
                        .addGap(146, 146, 146)
                        .addComponent(jLabelDestino))
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addComponent(jLabelSalida)
                        .addGap(156, 156, 156)
                        .addComponent(jLabelArribo)
                        .addGap(162, 162, 162)
                        .addComponent(jLabelEstado)
                        .addGap(19, 19, 19)
                        .addComponent(jLabelAsiento))
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addComponent(jLabelAerolinea)
                        .addGap(218, 218, 218)
                        .addComponent(jLabelAeronave))
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addComponent(jDateChooserSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jDateChooserArribo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanelFondoSeleccionLayout.setVerticalGroup(
            jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAerolinea)
                    .addComponent(jLabelAeronave))
                .addGap(1, 1, 1)
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrigen)
                    .addComponent(jLabelDestino))
                .addGap(2, 2, 2)
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSalida)
                    .addComponent(jLabelArribo)
                    .addComponent(jLabelEstado)
                    .addComponent(jLabelAsiento))
                .addGap(1, 1, 1)
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserArribo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel.add(jPanelFondoSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 360, 695, 220));

        jButtonEliminar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("- Eliminar vuelo");
        jButtonEliminar.setBorder(null);
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        JPanel.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 590, 159, 31));

        jButtonModificar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonModificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("/ Modificar vuelo");
        jButtonModificar.setBorder(null);
        jButtonModificar.setBorderPainted(false);
        jButtonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        JPanel.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 590, 159, 31));

        jButtonAgregar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("+ Agregar vuelo");
        jButtonAgregar.setBorder(null);
        jButtonAgregar.setBorderPainted(false);
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        JPanel.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 159, 31));

        jButtonBuscar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("ó Buscar vuelo");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        JPanel.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 159, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jTableVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVuelosMouseClicked
        llenarCampos();
        jButtonAsientos.setEnabled(true);
        mostrarAsientos();
    }//GEN-LAST:event_jTableVuelosMouseClicked

    private void jLabelAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAdministradorMouseClicked
        ventana.setVisible(false);
        VistaAdmin.visibilidad(true);
    }//GEN-LAST:event_jLabelAdministradorMouseClicked

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        if (!camposVacios()) {
            if (0 == JOptionPane.showConfirmDialog(this, "¿Esta seguro de hacer este registro?")) {
                Ciudad origen = cD.getCiudadPorNombre(jComboBoxOrigen.getSelectedItem().toString());
                Ciudad destino = cD.getCiudadPorNombre(jComboBoxDestino.getSelectedItem().toString());
                Date salida = jDateChooserSalida.getDate();
                Date arribo = jDateChooserArribo.getDate();
                Vuelo nuevoVuelo = new Vuelo(jComboBoxAerolinea.getSelectedItem().toString(), jComboBoxAeronave.getSelectedItem().toString(), origen, destino, salida, arribo, jComboBoxEstado.getSelectedItem().toString());
                float precio = Float.parseFloat(jTextFieldPrecio.getText());
                Asiento asientoVuelo = new Asiento(precio);
                try {
                    vD.altaVuelo(nuevoVuelo, asientoVuelo);
                    JOptionPane.showMessageDialog(null, "Registro exitoso!");
                    llenarTabla();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error al agregar nuevo vuelo a la db!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error. Debe llenar todos los campos");
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        int fila = jTableVuelos.getSelectedRow();
        String idAux = jTableVuelos.getValueAt(fila, 0).toString();
        int id = Integer.parseInt(idAux);
        
        List<String> mails = vD.obtenerMailClientesVuelo(vD.buscarVuelo(id));

        if (!camposVacios()) {
            if (0 == JOptionPane.showConfirmDialog(this, "¿Esta seguro de hacer esta modificacion?")) {
                Ciudad origen = cD.getCiudadPorNombre(jComboBoxOrigen.getSelectedItem().toString());
                Ciudad destino = cD.getCiudadPorNombre(jComboBoxDestino.getSelectedItem().toString());
                Date salida = jDateChooserSalida.getDate();
                Date arribo = jDateChooserArribo.getDate();
                Vuelo vueloModificado = new Vuelo(id, jComboBoxAerolinea.getSelectedItem().toString(), jComboBoxAeronave.getSelectedItem().toString(), origen, destino, salida, arribo, jComboBoxEstado.getSelectedItem().toString());
                try {
                    switch (vueloModificado.getEstado()) {
                        case "c":
                            if (jTableVuelos.getValueAt(fila, 7).toString().equals("N") || jTableVuelos.getValueAt(fila, 7).toString().equals("D")) {
                                for (int i = 0 ; i < mails.size() ; i++) {
                                    enviarCorreo ("vuelos032@gmail.com" , "vuelos123456" , mails.get(i) , "Vuelo cancelado" , "Estimado cliente. Lamentamos informale que su vuelo con id: "+id+", ha sido cancelado. Lamentamos las molestias. Saludos. Equipo de Vuelos32");
                                }
                            }
                            break;
                        case "n":
                            if (jTableVuelos.getValueAt(fila, 7).toString().equals("D") || jTableVuelos.getValueAt(fila, 7).toString().equals("C")) {
                                for (int i = 0 ; i < mails.size() ; i++) {
                                    enviarCorreo ("vuelos032@gmail.com" , "vuelos123456" , mails.get(i) , "Vuelo normalizado" , "Estimado cliente. Le informamos que su vuelo con id: "+id+", se ha normalizado. Saludos. Equipo de Vuelos32");
                                }
                            }
                            break;
                        case "d":
                            if (jTableVuelos.getValueAt(fila, 7).toString().equals("N") || jTableVuelos.getValueAt(fila, 7).toString().equals("C")) {
                                for (int i = 0 ; i < mails.size() ; i++) {
                                    enviarCorreo ("vuelos032@gmail.com" , "vuelos123456" , mails.get(i) , "Vuelo demorado" , "Estimado cliente. Le informamos que su vuelo con id: "+id+", se encuentra demorado. Saludos. Equipo de Vuelos32");
                                }
                            }
                            break;
                    }
                    vD.modificarVuelo(vueloModificado);
                    JOptionPane.showMessageDialog(null, "Modificación exitosa!");
                    llenarTabla();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "No se pudo realizar la modificación");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error. Debe llenar todos los campos");
        }
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int fila = jTableVuelos.getSelectedRow();
        String idAux = jTableVuelos.getValueAt(fila, 0).toString();
        int id = Integer.parseInt(idAux);

        if (0 == JOptionPane.showConfirmDialog(this, "¿Esta seguro de eliminar este vuelo?")) {
            try {
                vD.bajaVuelo(id);
                JOptionPane.showMessageDialog(null, "Se ha eliminado el vuelo exitosamente");
                llenarTabla();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al eliminar vuelo");
            }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsientosActionPerformed
        jPanelAsientos.setVisible(true);
        jPanelFondoAsientos.setVisible(true);
    }//GEN-LAST:event_jButtonAsientosActionPerformed

    private void jPanelFondoAsientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFondoAsientosMouseClicked
        jPanelAsientos.setVisible(false);
        jPanelFondoAsientos.setVisible(false);
    }//GEN-LAST:event_jPanelFondoAsientosMouseClicked

    private void jButtonV001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV001ActionPerformed
        cambiarDisponible(jButtonV001, "V001");
    }//GEN-LAST:event_jButtonV001ActionPerformed

    private void jButtonP002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP002ActionPerformed
        cambiarDisponible(jButtonP002, "P002");
    }//GEN-LAST:event_jButtonP002ActionPerformed

    private void jButtonV004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV004ActionPerformed
        cambiarDisponible(jButtonV004, "V004");
    }//GEN-LAST:event_jButtonV004ActionPerformed

    private void jButtonP003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP003ActionPerformed
        cambiarDisponible(jButtonP003, "P003");
    }//GEN-LAST:event_jButtonP003ActionPerformed

    private void jButtonV005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV005ActionPerformed
        cambiarDisponible(jButtonV005, "V005");
    }//GEN-LAST:event_jButtonV005ActionPerformed

    private void jButtonP006ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP006ActionPerformed
        cambiarDisponible(jButtonP006, "P006");
    }//GEN-LAST:event_jButtonP006ActionPerformed

    private void jButtonP007ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP007ActionPerformed
        cambiarDisponible(jButtonP007, "P007");
    }//GEN-LAST:event_jButtonP007ActionPerformed

    private void jButtonV008ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV008ActionPerformed
        cambiarDisponible(jButtonV008, "V008");
    }//GEN-LAST:event_jButtonV008ActionPerformed

    private void jButtonV009ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV009ActionPerformed
        cambiarDisponible(jButtonV009, "V009");
    }//GEN-LAST:event_jButtonV009ActionPerformed

    private void jButtonP010ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP010ActionPerformed
        cambiarDisponible(jButtonP010, "P010");
    }//GEN-LAST:event_jButtonP010ActionPerformed

    private void jButtonP011ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP011ActionPerformed
        cambiarDisponible(jButtonP011, "P011");
    }//GEN-LAST:event_jButtonP011ActionPerformed

    private void jButtonV012ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV012ActionPerformed
        cambiarDisponible(jButtonV012, "V012");
    }//GEN-LAST:event_jButtonV012ActionPerformed

    private void jButtonV013ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV013ActionPerformed
        cambiarDisponible(jButtonV013, "V013");
    }//GEN-LAST:event_jButtonV013ActionPerformed

    private void jButtonP014ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP014ActionPerformed
        cambiarDisponible(jButtonP014, "P014");
    }//GEN-LAST:event_jButtonP014ActionPerformed

    private void jButtonP015ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP015ActionPerformed
        cambiarDisponible(jButtonP015, "P015");
    }//GEN-LAST:event_jButtonP015ActionPerformed

    private void jButtonV016ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV016ActionPerformed
        cambiarDisponible(jButtonV016, "V016");
    }//GEN-LAST:event_jButtonV016ActionPerformed

    private void jButtonV017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV017ActionPerformed
        cambiarDisponible(jButtonV017, "V017");
    }//GEN-LAST:event_jButtonV017ActionPerformed

    private void jButtonP018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP018ActionPerformed
        cambiarDisponible(jButtonP018, "P018");
    }//GEN-LAST:event_jButtonP018ActionPerformed

    private void jButtonP019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP019ActionPerformed
        cambiarDisponible(jButtonP019, "P019");
    }//GEN-LAST:event_jButtonP019ActionPerformed

    private void jButtonV020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV020ActionPerformed
        cambiarDisponible(jButtonV020, "V020");
    }//GEN-LAST:event_jButtonV020ActionPerformed

    private void jButtonV021ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV021ActionPerformed
        cambiarDisponible(jButtonV021, "V021");
    }//GEN-LAST:event_jButtonV021ActionPerformed

    private void jButtonP022ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP022ActionPerformed
        cambiarDisponible(jButtonP022, "P022");
    }//GEN-LAST:event_jButtonP022ActionPerformed

    private void jButtonP023ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP023ActionPerformed
        cambiarDisponible(jButtonP023, "P023");
    }//GEN-LAST:event_jButtonP023ActionPerformed

    private void jButtonV024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV024ActionPerformed
        cambiarDisponible(jButtonV024, "V024");
    }//GEN-LAST:event_jButtonV024ActionPerformed

    private void jButtonV025ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV025ActionPerformed
        cambiarDisponible(jButtonV025, "V025");
    }//GEN-LAST:event_jButtonV025ActionPerformed

    private void jButtonP026ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP026ActionPerformed
        cambiarDisponible(jButtonP026, "P026");
    }//GEN-LAST:event_jButtonP026ActionPerformed

    private void jButtonP027ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP027ActionPerformed
        cambiarDisponible(jButtonP027, "P027");
    }//GEN-LAST:event_jButtonP027ActionPerformed

    private void jButtonV028ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV028ActionPerformed
        cambiarDisponible(jButtonV028, "V028");
    }//GEN-LAST:event_jButtonV028ActionPerformed

    private void jButtonV029ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV029ActionPerformed
        cambiarDisponible(jButtonV029, "V029");
    }//GEN-LAST:event_jButtonV029ActionPerformed

    private void jButtonP030ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP030ActionPerformed
        cambiarDisponible(jButtonP030, "P030");
    }//GEN-LAST:event_jButtonP030ActionPerformed

    private void jButtonP031ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonP031ActionPerformed
        cambiarDisponible(jButtonP031, "P031");
    }//GEN-LAST:event_jButtonP031ActionPerformed

    private void jButtonV032ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonV032ActionPerformed
        cambiarDisponible(jButtonV032, "V032");
    }//GEN-LAST:event_jButtonV032ActionPerformed

    private void jButtonLimpiarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarFiltrosActionPerformed
        modelo = (DefaultTableModel) jTableVuelos.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(modelo);
        jTableVuelos.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(""));
        llenarTabla();
    }//GEN-LAST:event_jButtonLimpiarFiltrosActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        modelo = (DefaultTableModel) jTableVuelos.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(modelo);
        jTableVuelos.setRowSorter(tr);
        List<RowFilter<DefaultTableModel, Object>> filtros = new ArrayList<>();
        int i = 0;
        if (!jComboBoxAerolinea.getSelectedItem().toString().equals("Seleccione una aerolinea")) {
            filtros.add(RowFilter.regexFilter(jComboBoxAerolinea.getSelectedItem().toString().toUpperCase(),1));
            filtros.set(i, RowFilter.regexFilter(jComboBoxAerolinea.getSelectedItem().toString().toUpperCase(),1));
            i += 1;
        }
        if (!jComboBoxAeronave.getSelectedItem().toString().equals("Seleccione una aeronave")) {
            filtros.add(RowFilter.regexFilter(jComboBoxAeronave.getSelectedItem().toString().toUpperCase(),2));
            filtros.set(i, RowFilter.regexFilter(jComboBoxAeronave.getSelectedItem().toString().toUpperCase(),2));
            i += 1;
        }
        if (!jComboBoxOrigen.getSelectedItem().toString().equals("Seleccione ciudad de origen")) {
            filtros.add(RowFilter.regexFilter(jComboBoxOrigen.getSelectedItem().toString().toUpperCase(),3));
            filtros.set(i, RowFilter.regexFilter(jComboBoxOrigen.getSelectedItem().toString().toUpperCase(),3));
            i += 1;
        }
        if (!jComboBoxDestino.getSelectedItem().toString().equals("Seleccione ciudad de destino")) {
            filtros.add(RowFilter.regexFilter(jComboBoxDestino.getSelectedItem().toString().toUpperCase(),4));
            filtros.set(i, RowFilter.regexFilter(jComboBoxDestino.getSelectedItem().toString().toUpperCase(),4));
            i += 1;
        }
        if (jDateChooserSalida.getDate() != null) {
            filtros.add(RowFilter.regexFilter(new SimpleDateFormat("dd/MM/yyyy").format(jDateChooserSalida.getDate()),5));
            filtros.set(i, RowFilter.regexFilter(new SimpleDateFormat("dd/MM/yyyy").format(jDateChooserSalida.getDate()),5));
            i += 1;
        }
        if (jDateChooserArribo.getDate() != null) {
            filtros.add(RowFilter.regexFilter(new SimpleDateFormat("dd/MM/yyyy").format(jDateChooserArribo.getDate()),6));
            filtros.set(i, RowFilter.regexFilter(new SimpleDateFormat("dd/MM/yyyy").format(jDateChooserArribo.getDate()),6));
            i += 1;
        }
        if (!jComboBoxEstado.getSelectedItem().toString().equals("Estado")) {
            filtros.add(RowFilter.regexFilter(jComboBoxEstado.getSelectedItem().toString().toUpperCase(),7));
            filtros.set(i, RowFilter.regexFilter(jComboBoxEstado.getSelectedItem().toString().toUpperCase(),7));
            i += 1;
        }
        tr.setRowFilter(RowFilter.andFilter(filtros));
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisponiblesActionPerformed
        llenarTablaDisponibles();
    }//GEN-LAST:event_jButtonDisponiblesActionPerformed

    private void jLabelInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMouseClicked
        ventana.setVisible(false);
        VistaVueloCliente.visibilidad(true);
    }//GEN-LAST:event_jLabelInicioMouseClicked

    private void jTextFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "El campo Precio sólo admite números");
        }
        if (jTextFieldPrecio.getText().length() == 10) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "El campo Precio sólo admite números con hasta 10 dígitos");
        }
    }//GEN-LAST:event_jTextFieldPrecioKeyTyped

    public void llenarTabla() {
        List<Vuelo> vuelos = vD.obtenerVuelos();
        modelo = (DefaultTableModel) jTableVuelos.getModel();
        modelo.setRowCount(0);
        Object[] fila = new Object[modelo.getColumnCount()];
        for (int i = 0; i < vuelos.size(); i++) {
            fila[0] = vuelos.get(i).getIdVuelo();
            fila[1] = vuelos.get(i).getAerolinea().toUpperCase();
            fila[2] = vuelos.get(i).getTipoAeronave().toUpperCase();
            Ciudad origen = cD.getCiudad(vuelos.get(i).getCiudadOrigen().getIdCiudad());
            fila[3] = origen.getNombre().toUpperCase();
            Ciudad destino = cD.getCiudad(vuelos.get(i).getCiudadDestino().getIdCiudad());
            fila[4] = destino.getNombre().toUpperCase();
            fila[5] = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(vuelos.get(i).getFechaSalida());
            fila[6] = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(vuelos.get(i).getFechaArribo());
            fila[7] = vuelos.get(i).getEstado().toUpperCase();
            modelo.addRow(fila);
        }
    }
    
    public void llenarTablaDisponibles() {
        List<Vuelo> vuelos = vD.obtenerVuelos();
        modelo = (DefaultTableModel) jTableVuelos.getModel();
        modelo.setRowCount(0);
        Object[] fila = new Object[modelo.getColumnCount()];
        int i = 0;
        while (i < vuelos.size()) {
            if (!vuelos.get(i).getEstado().equals("c") && vuelos.get(i).getFechaSalida().after(new Date())) {
                fila[0] = vuelos.get(i).getIdVuelo();
                fila[1] = vuelos.get(i).getAerolinea().toUpperCase();
                fila[2] = vuelos.get(i).getTipoAeronave().toUpperCase();
                Ciudad origen = cD.getCiudad(vuelos.get(i).getCiudadOrigen().getIdCiudad());
                fila[3] = origen.getNombre().toUpperCase();
                Ciudad destino = cD.getCiudad(vuelos.get(i).getCiudadDestino().getIdCiudad());
                fila[4] = destino.getNombre().toUpperCase();
                fila[5] = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(vuelos.get(i).getFechaSalida());
                fila[6] = new SimpleDateFormat("dd/MM/yyyy HH:mm").format(vuelos.get(i).getFechaArribo());
                fila[7] = vuelos.get(i).getEstado().toUpperCase();
                modelo.addRow(fila);
            }
            i++;
        }
    }

    public void llenarCampos() {
        int fila = jTableVuelos.getSelectedRow();
        String id_aux = jTableVuelos.getValueAt(fila, 0).toString();
        int id = Integer.parseInt(id_aux);

        Vuelo vuelo = vD.buscarVuelo(id);
        jComboBoxAerolinea.setSelectedItem(vuelo.getAerolinea());
        jComboBoxAeronave.setSelectedItem(vuelo.getTipoAeronave());
        Ciudad origen = cD.getCiudad(vuelo.getCiudadOrigen().getIdCiudad());
        jComboBoxOrigen.setSelectedItem(origen.getNombre());
        Ciudad destino = cD.getCiudad(vuelo.getCiudadDestino().getIdCiudad());
        jComboBoxDestino.setSelectedItem(destino.getNombre());
        jDateChooserSalida.setDate(vuelo.getFechaSalida());
        jDateChooserArribo.setDate(vuelo.getFechaArribo());
        jComboBoxEstado.setSelectedItem(vuelo.getEstado());
        Asiento asiento = aD.buscarAsientoPorVuelo(vuelo);
        jTextFieldPrecio.setText("" + asiento.getPrecio());
    }

    public void llenarComboCiudades() {
        DefaultComboBoxModel modeloOrigen = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloDestino = new DefaultComboBoxModel();
        List<Ciudad> ciudades = cD.getCiudades();
        modeloOrigen.addElement("Seleccione ciudad de origen");
        jComboBoxOrigen.setModel(modeloOrigen);
        modeloDestino.addElement("Seleccione ciudad de destino");
        jComboBoxDestino.setModel(modeloDestino);
        for (int i = 0; i < ciudades.size(); i++) {
            modeloOrigen.addElement(ciudades.get(i).getNombre());
            jComboBoxOrigen.setModel(modeloOrigen);
            modeloDestino.addElement(ciudades.get(i).getNombre());
            jComboBoxDestino.setModel(modeloDestino);
        }
    }

    public void mostrarAsientos() {
        pintarBotonAsiento(jButtonV001, "V001");
        pintarBotonAsiento(jButtonP002, "P002");
        pintarBotonAsiento(jButtonP003, "P003");
        pintarBotonAsiento(jButtonV004, "V004");
        pintarBotonAsiento(jButtonV005, "V005");
        pintarBotonAsiento(jButtonP006, "P006");
        pintarBotonAsiento(jButtonP007, "P007");
        pintarBotonAsiento(jButtonV008, "V008");
        pintarBotonAsiento(jButtonV009, "V009");
        pintarBotonAsiento(jButtonP010, "P010");
        pintarBotonAsiento(jButtonP011, "P011");
        pintarBotonAsiento(jButtonV012, "V012");
        pintarBotonAsiento(jButtonV013, "V013");
        pintarBotonAsiento(jButtonP014, "P014");
        pintarBotonAsiento(jButtonP015, "P015");
        pintarBotonAsiento(jButtonV016, "V016");
        pintarBotonAsiento(jButtonV017, "V017");
        pintarBotonAsiento(jButtonP018, "P018");
        pintarBotonAsiento(jButtonP019, "P019");
        pintarBotonAsiento(jButtonV020, "V020");
        pintarBotonAsiento(jButtonV021, "V021");
        pintarBotonAsiento(jButtonP022, "P022");
        pintarBotonAsiento(jButtonP023, "P023");
        pintarBotonAsiento(jButtonV024, "V024");
        pintarBotonAsiento(jButtonV025, "V025");
        pintarBotonAsiento(jButtonP026, "P026");
        pintarBotonAsiento(jButtonP027, "P027");
        pintarBotonAsiento(jButtonV028, "V028");
        pintarBotonAsiento(jButtonV029, "V029");
        pintarBotonAsiento(jButtonP030, "P030");
        pintarBotonAsiento(jButtonP031, "P031");
        pintarBotonAsiento(jButtonV032, "V032");
    }

    public void pintarBotonAsiento(JButton boton, String ubicacion) {
        int fila = jTableVuelos.getSelectedRow();
        String id_aux = jTableVuelos.getValueAt(fila, 0).toString();
        int id = Integer.parseInt(id_aux);
        Vuelo vuelo = vD.buscarVuelo(id);
        Asiento asiento = aD.obtenerAsientosVueloUbicacion(vuelo, ubicacion);
        if (!asiento.getDisponible()) {
            boton.setBackground(Color.red);
        } else {
            boton.setBackground(new java.awt.Color(153, 204, 51));
        }
    }

    public void cambiarDisponible(JButton boton, String ubicacion) {
        int fila = jTableVuelos.getSelectedRow();
        String id_aux = jTableVuelos.getValueAt(fila, 0).toString();
        int id = Integer.parseInt(id_aux);
        Vuelo vuelo = vD.buscarVuelo(id);
        Asiento asiento = aD.obtenerAsientosVueloUbicacion(vuelo, ubicacion);
        if (asiento.getDisponible()) {
            asiento.setDisponible(false);
            boton.setBackground(Color.red);
        } else {
            asiento.setDisponible(true);
            boton.setBackground(new java.awt.Color(153, 204, 51));
        }
        aD.actualizarAsiento(asiento);
    }

    private boolean camposVacios() {
        boolean hayVacias = false;
        if (jComboBoxAerolinea.getSelectedItem().equals("Seleccione una aerolinea") || jComboBoxAeronave.getSelectedItem().equals("Seleccione una aeronave")
                || jComboBoxOrigen.getSelectedItem().toString().equals("Seleccione ciudad de origen")
                || jComboBoxDestino.getSelectedItem().toString().equals("Seleccione ciudad de destino")
                || jDateChooserArribo.getDate() == null || jDateChooserArribo.getDate() == null
                || jComboBoxEstado.getSelectedItem().equals("Estado") || jTextFieldPrecio.getText().equals("")) {
            hayVacias = true;
        }
        return hayVacias;
    }
    
    public void enviarCorreo(String usuario, String contraseña, String destinatario, String asunto, String mensaje) {
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(usuario, contraseña);
                    }
                });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(usuario));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(destinatario));
            message.setSubject(asunto);
            message.setText(mensaje);

            Transport.send(message);
            JOptionPane.showMessageDialog(this, "Su mensaje ha sido enviado");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }

    public static void visibilidad(boolean estado) {
        ventana.setVisible(estado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAsientos;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDisponibles;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonLimpiarFiltros;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonP002;
    private javax.swing.JButton jButtonP003;
    private javax.swing.JButton jButtonP006;
    private javax.swing.JButton jButtonP007;
    private javax.swing.JButton jButtonP010;
    private javax.swing.JButton jButtonP011;
    private javax.swing.JButton jButtonP014;
    private javax.swing.JButton jButtonP015;
    private javax.swing.JButton jButtonP018;
    private javax.swing.JButton jButtonP019;
    private javax.swing.JButton jButtonP022;
    private javax.swing.JButton jButtonP023;
    private javax.swing.JButton jButtonP026;
    private javax.swing.JButton jButtonP027;
    private javax.swing.JButton jButtonP030;
    private javax.swing.JButton jButtonP031;
    private javax.swing.JButton jButtonV001;
    private javax.swing.JButton jButtonV004;
    private javax.swing.JButton jButtonV005;
    private javax.swing.JButton jButtonV008;
    private javax.swing.JButton jButtonV009;
    private javax.swing.JButton jButtonV012;
    private javax.swing.JButton jButtonV013;
    private javax.swing.JButton jButtonV016;
    private javax.swing.JButton jButtonV017;
    private javax.swing.JButton jButtonV020;
    private javax.swing.JButton jButtonV021;
    private javax.swing.JButton jButtonV024;
    private javax.swing.JButton jButtonV025;
    private javax.swing.JButton jButtonV028;
    private javax.swing.JButton jButtonV029;
    private javax.swing.JButton jButtonV032;
    private javax.swing.JComboBox<String> jComboBoxAerolinea;
    private javax.swing.JComboBox<String> jComboBoxAeronave;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private com.toedter.calendar.JDateChooser jDateChooserArribo;
    private com.toedter.calendar.JDateChooser jDateChooserSalida;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelAerolinea;
    private javax.swing.JLabel jLabelAeronave;
    private javax.swing.JLabel jLabelArribo;
    private javax.swing.JLabel jLabelAsiento;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JLabel jLabelSalida;
    private javax.swing.JLabel jLabelVuelos;
    private javax.swing.JPanel jPanelAsientos;
    private javax.swing.JPanel jPanelFondoAsientos;
    private javax.swing.JPanel jPanelFondoSeleccion;
    private javax.swing.JScrollPane jScrollPaneVuelos;
    private javax.swing.JTable jTableVuelos;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
