/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Asiento;
import clases.Ciudad;
import clases.Cliente;
import clases.Compra;
import clases.Vuelo;
import clasesData.AsientoData;
import clasesData.CiudadData;
import clasesData.ClienteData;
import clasesData.CompraData;
import clasesData.VueloData;
import conexion.Conexion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author asus pc
 */
    public class VistaNuevaCompra extends javax.swing.JFrame {
    private static VistaNuevaCompra ventana = new VistaNuevaCompra();
    private TableRowSorter filtro;
    private VueloData vD = new VueloData();
    private CiudadData cD = new CiudadData();
    private AsientoData aD= new AsientoData();
    //private AsientoData aD = new AsientoData();
    private DefaultTableModel modelo;
    
//Atributos extras de la ventana asiento
   private List<JToggleButton> botones;
   private int indice;
   private static List<Asiento> listaAsientos;
    

    private List<Vuelo> listaVuelos;    
//Constructor
    public VistaNuevaCompra() {
        initComponents();
        llenarComboCiudades();
        //this.setLocationRelativeTo(null);
        //listaVuelos=vD.obtenerVuelos(); 
        //this.llenarTabla(listaVuelos);
         botones = new ArrayList<>();
        indice=0;
        AsientoData asientoData= new AsientoData();
        listaAsientos=asientoData.obtenerAsientos();
        panelContenedorAsientos.setVisible(false);
        
        jButtonDisponible.setBackground(Color.green);
        jButtonOcupado.setBackground(Color.red);
        
        jButtonDisponible.setVisible(false);
        jButtonOcupado.setVisible(false);
        
        //panel confirmar compra
        jPanelDatosPasaje.setVisible(false);
        panelDatosCliente.setVisible(false);
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        panelDatosCliente = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pasaporte = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        apellido = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tarjeta = new javax.swing.JLabel();
        cerrarPanelConfirmar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        mailCliente = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        nombreAerolinea1 = new javax.swing.JLabel();
        nombreCiudadOrigen1 = new javax.swing.JLabel();
        fechaSalida1 = new javax.swing.JLabel();
        ubicacionAsiento1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        nombreAeronave1 = new javax.swing.JLabel();
        nombreCiudadDestino1 = new javax.swing.JLabel();
        fechaArribo1 = new javax.swing.JLabel();
        precioAsiento1 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jPanelDatosPasaje = new javax.swing.JPanel();
        siguiente = new javax.swing.JButton();
        cerrarPanelDatosVuelo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreAerolinea = new javax.swing.JLabel();
        nombreAeronave = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreCiudadOrigen = new javax.swing.JLabel();
        fechaSalida = new javax.swing.JLabel();
        nombreCiudadDestino = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ubicacionAsiento = new javax.swing.JLabel();
        precioAsiento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaArribo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nroDni = new javax.swing.JTextField();
        nroPasaporte = new javax.swing.JTextField();
        nombreCliente = new javax.swing.JTextField();
        apellidoCliente = new javax.swing.JTextField();
        tarj1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        idAsientoComprado = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabelCompras = new javax.swing.JLabel();
        jLabelComprarAsiento = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelFondoSeleccion = new javax.swing.JPanel();
        jLabelOrigen = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jDateChooserSalida = new com.toedter.calendar.JDateChooser();
        jLabelSalida = new javax.swing.JLabel();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jButtonMostrarVuelos = new javax.swing.JButton();
        jLabelVuelta = new javax.swing.JLabel();
        jDateChooserVuelta = new com.toedter.calendar.JDateChooser();
        jButtonAtras = new javax.swing.JButton();
        limpiarVuelos = new javax.swing.JButton();
        jButtonVerAsientos = new javax.swing.JButton();
        panelContenedorAsientos = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jScrollPaneVuelos = new javax.swing.JScrollPane();
        jTableVuelos = new javax.swing.JTable();
        jButtonDisponible = new javax.swing.JButton();
        jButtonOcupado = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 204, 0));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        JPanel.setBackground(new java.awt.Color(153, 204, 51));
        JPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatosCliente.setBackground(new java.awt.Color(102, 153, 51));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Dni:");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nro Pasaporte:");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nombre:");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Apellido:");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Nro de Tarjeta:");

        cerrarPanelConfirmar.setText("Cancelar");
        cerrarPanelConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPanelConfirmarActionPerformed(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Correo Electronico:");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Asiento:");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Fecha Salida:");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Ciudad Origen:");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Aerolinea:");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Datos del Vuelo");

        nombreAerolinea1.setText("-");

        nombreCiudadOrigen1.setText("cO");

        fechaSalida1.setText("fS");

        ubicacionAsiento1.setText("Cod");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Precio:");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Fecha de Arribo:");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Ciudad Destino:");

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Aeronave:");

        nombreAeronave1.setText("-");

        nombreCiudadDestino1.setText("cD");

        fechaArribo1.setText("fA");

        precioAsiento1.setText("Pre");

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Confirmar Pasaje - Revise Los datos");

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Datos de Usuario");

        javax.swing.GroupLayout panelDatosClienteLayout = new javax.swing.GroupLayout(panelDatosCliente);
        panelDatosCliente.setLayout(panelDatosClienteLayout);
        panelDatosClienteLayout.setHorizontalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreCiudadOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioAsiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreAerolinea1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel36)
                    .addComponent(jLabel30))
                .addGap(88, 88, 88))
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addGap(125, 125, 125))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(mailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cerrarPanelConfirmar))
                                    .addComponent(tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(14, 14, 14)
                                .addComponent(pasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ubicacionAsiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreCiudadDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fechaArribo1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreAeronave1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDatosClienteLayout.setVerticalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosClienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel34)
                    .addComponent(nombreAerolinea1)
                    .addComponent(nombreAeronave1))
                .addGap(18, 18, 18)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(nombreCiudadOrigen1)
                    .addComponent(nombreCiudadDestino1)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(fechaArribo1)
                        .addComponent(fechaSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(ubicacionAsiento1)
                    .addComponent(jLabel31)
                    .addComponent(precioAsiento1))
                .addGap(33, 33, 33)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cerrarPanelConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel.add(panelDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 390, 420));

        jLabelInicio.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(102, 153, 51));
        jLabelInicio.setText("Inicio //");
        jLabelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JPanel.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 20, 98, 30));

        jPanelDatosPasaje.setBackground(new java.awt.Color(102, 153, 51));

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        cerrarPanelDatosVuelo.setText("Cancelar");
        cerrarPanelDatosVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarPanelDatosVueloActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos del Vuelo");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aerolinea:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aeronave:");

        nombreAerolinea.setText("-");

        nombreAeronave.setText("-");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ciudad Origen:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ciudad Destino:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Salida:");

        nombreCiudadOrigen.setText("cO");

        fechaSalida.setText("fS");

        nombreCiudadDestino.setText("cD");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Asiento:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Precio:");

        ubicacionAsiento.setText("Cod");

        precioAsiento.setText("Pre");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha de Arribo:");

        fechaArribo.setText("fA");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Datos Personales");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dni:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nro de Tarjeta:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Nro de Pasaporte:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Apellido:");

        nroPasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nroPasaporteActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Ingrese sus Datos!");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        resultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        idAsientoComprado.setText("--");

        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo Electronico");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosPasajeLayout = new javax.swing.GroupLayout(jPanelDatosPasaje);
        jPanelDatosPasaje.setLayout(jPanelDatosPasajeLayout);
        jPanelDatosPasajeLayout.setHorizontalGroup(
            jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreCiudadOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(precioAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(idAsientoComprado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62))
                                    .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                        .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fechaArribo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nombreCiudadDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(nombreAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(nombreAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(250, 250, 250))
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16))
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ubicacionAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                        .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel15))
                                    .addComponent(tarj1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                        .addComponent(siguiente)
                                        .addGap(15, 15, 15)
                                        .addComponent(cerrarPanelDatosVuelo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nroPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(40, 40, 40)
                                .addComponent(nroDni, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                                .addComponent(jLabelCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelDatosPasajeLayout.setVerticalGroup(
            jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPasajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(nombreAerolinea)
                    .addComponent(nombreAeronave))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(nombreCiudadOrigen)
                        .addComponent(nombreCiudadDestino)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaSalida)
                    .addComponent(jLabel4)
                    .addComponent(fechaArribo))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ubicacionAsiento)
                    .addComponent(jLabel13)
                    .addComponent(precioAsiento)
                    .addComponent(jLabel21)
                    .addComponent(idAsientoComprado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nroDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nroPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tarj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCorreo)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPasajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente)
                    .addComponent(cerrarPanelDatosVuelo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel.add(jPanelDatosPasaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 460, 420));

        jLabelCompras.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabelCompras.setForeground(new java.awt.Color(102, 153, 51));
        jLabelCompras.setText("Compras /");
        jLabelCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelComprasMouseClicked(evt);
            }
        });
        JPanel.add(jLabelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 20, -1, 30));

        jLabelComprarAsiento.setBackground(new java.awt.Color(102, 153, 51));
        jLabelComprarAsiento.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabelComprarAsiento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelComprarAsiento.setText("Compra Pasaje");
        JPanel.add(jLabelComprarAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 30));
        jLabelComprarAsiento.getAccessibleContext().setAccessibleName("Comprar Vuelo");

        jLabelCerrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(102, 153, 51));
        jLabelCerrar.setText("X");
        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        JPanel.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 15, 15));

        jPanelFondoSeleccion.setBackground(new java.awt.Color(102, 153, 51));

        jLabelOrigen.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelOrigen.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrigen.setText("Origen");

        jLabelDestino.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDestino.setText("Destino");

        jDateChooserSalida.setBackground(new java.awt.Color(102, 153, 51));
        jDateChooserSalida.setToolTipText("");
        jDateChooserSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooserSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDateChooserSalidaMouseEntered(evt);
            }
        });

        jLabelSalida.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelSalida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalida.setText("Salida");

        jComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrigenActionPerformed(evt);
            }
        });

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonBuscar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonBuscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.setLabel("Buscar Vuelos");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonMostrarVuelos.setBackground(new java.awt.Color(102, 153, 51));
        jButtonMostrarVuelos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonMostrarVuelos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMostrarVuelos.setText("Todos los Vuelos");
        jButtonMostrarVuelos.setToolTipText("");
        jButtonMostrarVuelos.setBorder(null);
        jButtonMostrarVuelos.setBorderPainted(false);
        jButtonMostrarVuelos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMostrarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarVuelosActionPerformed(evt);
            }
        });

        jLabelVuelta.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelVuelta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVuelta.setText("Vuelta");

        jDateChooserVuelta.setBackground(new java.awt.Color(102, 153, 51));
        jDateChooserVuelta.setToolTipText("");
        jDateChooserVuelta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooserVueltaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jDateChooserVueltaMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanelFondoSeleccionLayout = new javax.swing.GroupLayout(jPanelFondoSeleccion);
        jPanelFondoSeleccion.setLayout(jPanelFondoSeleccionLayout);
        jPanelFondoSeleccionLayout.setHorizontalGroup(
            jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrigen)
                    .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDestino)
                        .addGap(47, 47, 47)))
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addComponent(jDateChooserSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooserVuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMostrarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addComponent(jLabelSalida)
                        .addGap(54, 54, 54)
                        .addComponent(jLabelVuelta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFondoSeleccionLayout.setVerticalGroup(
            jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFondoSeleccionLayout.createSequentialGroup()
                        .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSalida)
                            .addComponent(jLabelDestino)
                            .addComponent(jLabelVuelta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooserSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateChooserVuelta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonMostrarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabelOrigen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel.add(jPanelFondoSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 870, 80));

        jButtonAtras.setBackground(new java.awt.Color(102, 153, 51));
        jButtonAtras.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setText("Salir");
        jButtonAtras.setBorder(null);
        jButtonAtras.setBorderPainted(false);
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        JPanel.add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 80, 31));

        limpiarVuelos.setText("Limpiar");
        limpiarVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarVuelosMouseClicked(evt);
            }
        });
        limpiarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarVuelosActionPerformed(evt);
            }
        });
        JPanel.add(limpiarVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        jButtonVerAsientos.setText("Ver Asientos");
        jButtonVerAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerAsientosActionPerformed(evt);
            }
        });
        JPanel.add(jButtonVerAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 100, -1));

        panel.setLayout(new java.awt.GridLayout(0, 2));

        panel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabel23.setText("Seleccione un Asiento");

        jLabel24.setText("Precio:");

        javax.swing.GroupLayout panelContenedorAsientosLayout = new javax.swing.GroupLayout(panelContenedorAsientos);
        panelContenedorAsientos.setLayout(panelContenedorAsientosLayout);
        panelContenedorAsientosLayout.setHorizontalGroup(
            panelContenedorAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorAsientosLayout.createSequentialGroup()
                .addGroup(panelContenedorAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorAsientosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenedorAsientosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel23)))
                .addGap(18, 18, 18)
                .addGroup(panelContenedorAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorAsientosLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorAsientosLayout.setVerticalGroup(
            panelContenedorAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorAsientosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelContenedorAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelContenedorAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24))
                    .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelContenedorAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        JPanel.add(panelContenedorAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 390, 320));

        jTableVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idVuelo", "Aerolinea", "Aeronave", "Origen", "Destino", "Salida", "Arribo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableVuelos.setToolTipText("");
        jTableVuelos.setSelectionBackground(new java.awt.Color(102, 153, 51));
        jTableVuelos.getTableHeader().setReorderingAllowed(false);
        jTableVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVuelosMouseClicked(evt);
            }
        });
        jScrollPaneVuelos.setViewportView(jTableVuelos);

        JPanel.add(jScrollPaneVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 460, 320));

        jButtonDisponible.setBackground(java.awt.Color.green);
        jButtonDisponible.setText("Disponible");
        jButtonDisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisponibleActionPerformed(evt);
            }
        });
        JPanel.add(jButtonDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, 40));

        jButtonOcupado.setBackground(java.awt.Color.red);
        jButtonOcupado.setText("Ocupado");
        jButtonOcupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcupadoActionPerformed(evt);
            }
        });
        JPanel.add(jButtonOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void cambiarDisponible(JButton boton, String ubicacion) {
        int fila = jTableVuelos.getSelectedRow();
        String id_aux = jTableVuelos.getValueAt(fila, 0).toString();
        int id = Integer.parseInt(id_aux);
        Vuelo vuelo = vD.buscarVuelo(id);
        Asiento asiento = aD.obtenerAsientosVueloUbicacion(vuelo, ubicacion);
        if (asiento.getDisponible()) {
            asiento.setDisponible(false);
            boton.setBackground(Color.red);
        } else {
            asiento.setDisponible(true);
            boton.setBackground(new java.awt.Color(153, 204, 51));
        }
        aD.actualizarAsiento(asiento);
    }
    
     public void llenarCamposCliente(Cliente cliente) {
         nroPasaporte.setText(""+cliente.getPasaporte());
         nombreCliente.setText(""+cliente.getNombre());
         apellidoCliente.setText(""+cliente.getApellido());
         tarj1.setText(""+cliente.getTarjeta());
         email.setText(cliente.getMail());
     
     }
     public void vaciarCajasCliente(){ 
     nroDni.setText(""); resultado.setText("");
     nroPasaporte.setText("");nombreCliente.setText("");apellidoCliente.setText("");
     tarj1.setText("");
     email.setText("");
    }
    public void vaciarCajasDatosVuelo(){
        
        nombreAerolinea.setText("");
        nombreAeronave.setText("");
        nombreCiudadOrigen.setText("");
        nombreCiudadDestino.setText("");

        fechaSalida.setText("");
        fechaArribo.setText("");
       
        idAsientoComprado.setText("");
        ubicacionAsiento.setText("");
        precioAsiento.setText("");
       
    
    }
    
    
    /*  Creacion de asientos dinamicos*/
     public void mostrarAsientos(List<Asiento> listaAsientos){  
      
      precio.setText("$"+listaAsientos.get(1).getPrecio());
             
     for(int i=0; i<listaAsientos.size();i++){   
     System.out.println(listaAsientos.get(i).getDisponible());
     }
     boolean disponible;
     for(int i=0; i<16; i++) {
        //System.out.println(listaAsientos.get(i).getDisponible());
        //System.out.println(listaAsientos.get(i).getCodigoAsiento());
        disponible=listaAsientos.get(i).getDisponible();
        JToggleButton boton = new JToggleButton("Asiento"+(indice+1));
        System.out.println(listaAsientos.get(i).getCodigoAsiento()+listaAsientos.get(i).getDisponible());
        float precio=listaAsientos.get(i).getPrecio();
        if(listaAsientos.get(i).getDisponible()){
        boton.setBackground(Color.green);
        }else{boton.setBackground(Color.red);}
        boton.setName(""+listaAsientos.get(i).getIdAsiento());//nombre del asiente igual a la cantidad de asientos
        boton.setText(listaAsientos.get(i).getCodigoAsiento());
        panel.add(boton);
        boton.addActionListener(new ActionListener(){
                 @Override
                 public void actionPerformed(ActionEvent e) {
                     if (boton.getBackground()==Color.green){
                         boton.setBackground(Color.red);
                         boton.setFocusPainted(true);
                         jPanelDatosPasaje.setVisible(true);
                         llenarDatosVuelo(Integer.parseInt(boton.getName()));
                         
                     }else{
                         JOptionPane.showMessageDialog(null,"Ha Habilitado un asiento");
                         boton.setBackground(Color.green);
                         
                         
                       } 
                    }
            });
        botones.add(boton);
         
        indice++;
     }

     panel.updateUI();
 
     //2da parte de asientos
 for(int i=16; i<32; i++) {
  disponible=listaAsientos.get(i).getDisponible();
        JToggleButton boton = new JToggleButton("Asiento"+(indice+1));
        System.out.println(listaAsientos.get(i).getCodigoAsiento()+listaAsientos.get(i).getDisponible());
        
        if(listaAsientos.get(i).getDisponible()){
        boton.setBackground(Color.green);
        }else{boton.setBackground(Color.red);}
        boton.setName(""+listaAsientos.get(i).getIdAsiento());//nombre del asiente igual a la cantidad de asientos
        boton.setText(listaAsientos.get(i).getCodigoAsiento());
        //boton.setBackground(Color.green);
        panel1.add(boton);
        boton.addActionListener(new ActionListener(){
                 @Override
                 public void actionPerformed(ActionEvent e) {
                    if (boton.getBackground()==Color.green){
                         boton.setBackground(Color.red);
                         boton.setFocusPainted(true);
                         jPanelDatosPasaje.setVisible(true);
                         llenarDatosVuelo(Integer.parseInt(boton.getName()));
                         
                     }else{
                         JOptionPane.showMessageDialog(null,"Ha Habilitado un asiento");
                         boton.setBackground(Color.green);
                         
                         
                       } 
                    }
            });
        botones.add(boton);
         
        indice++;
     }

     panel.updateUI();
 }
    
  //fin creacion dinamica de asientos
     
    
    
    
    
    
    
    
    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jTableVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVuelosMouseClicked
        llenarCampos();
        jLabel23.remove(this);
        jLabel24.remove(this);
        precio.setText("");
        precio.remove(this);
        
        jButtonDisponible.setVisible(false);
        jButtonOcupado.setVisible(false);
        panelContenedorAsientos.setVisible(false);
        jButtonVerAsientos.setEnabled(true);
      
        
    }//GEN-LAST:event_jTableVuelosMouseClicked

    private void jLabelComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelComprasMouseClicked
        ventana.setVisible(false);
        VistaCompraAdmin.visibilidad(true);
    }//GEN-LAST:event_jLabelComprasMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
             List<Vuelo> listaVuelos = new ArrayList<>();
             //System.out.println(jDateChooserSalida.getDate().toString().length());
             //System.out.println(jDateChooserSalida.getDate());
                String ciudadOrigen;
                String ciudadDestino;
                Timestamp fechaSalida;
                Timestamp fechaVuelta;
                if (jComboBoxOrigen.getSelectedItem().toString()!="Seleccione ciudad de origen"){
                     ciudadOrigen=jComboBoxOrigen.getSelectedItem().toString();
                     
                 }else { ciudadOrigen=""; //JOptionPane.showMessageDialog(null,"Debe Ingresar Ciudad de Origen");
                       }
                 if(jComboBoxDestino.getSelectedItem().toString()!="Seleccione ciudad de destino"){
                     ciudadDestino=jComboBoxDestino.getSelectedItem().toString();
                 }else{ ciudadDestino=""; }
                //System.out.println(ciudadOrigen);
                //System.out.println(ciudadDestino);
                // System.out.println((jDateChooserSalida.getDate()==null));
                 if (jDateChooserSalida.getDate()==null){ fechaSalida=null; }
                 else{ Date date=jDateChooserSalida.getDate();
                 fechaSalida= new Timestamp(date.getTime()); // fechaSalida tiene la fecha en type timestamp con esta comparo la fecha de la base de datos
                  }  
                 
                  if (jDateChooserVuelta.getDate()==null){ fechaVuelta=null; }
                 else{ Date date=jDateChooserVuelta.getDate();
                 fechaVuelta= new Timestamp(date.getTime()); // fechaSalida tiene la fecha en type timestamp con esta comparo la fecha de la base de datos
                  } 
                      
                 // Buscar vuelos para la vuelta               
                /* if(jDateChooserVuelta.getDate()== null){ fechaVuelta=null; }                 
                 else{  Date date1=jDateChooserVuelta.getDate();
                 fechaVuelta= new Timestamp(date1.getTime());
                 }*/
                
                            
              /* java.sql.Timestamp currentTimestamp = new Timestamp (jDateChooserSalida.getDate().getTime());// a falta de una forma de hacerlo esta es otra
             System.out.println(new SimpleDateFormat("dd/MM/yyy HH:mm").format(currentTimestamp));*/
            
            //modelo.setRowCount(0);
            listaVuelos=vD.obtenerVuelosPorPreferencia(ciudadOrigen, ciudadDestino,fechaSalida, fechaVuelta);
            
            if(listaVuelos.size()>0){  
            llenarTabla(listaVuelos);
            }else { JOptionPane.showMessageDialog(null,"No se encontraron vuelos ");}             
         
                //LocalDate salida = jDateChooserSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                //LocalDate arribo = jDateChooserArribo.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
           
   
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonMostrarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarVuelosActionPerformed
       listaVuelos=vD.obtenerVuelosDisponiblesEnBD(); 
       this.llenarTabla(listaVuelos);        

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonMostrarVuelosActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
       ventana.setVisible(false);
       VistaCompraAdmin.visibilidad(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtrasActionPerformed
/**/
    private void jDateChooserSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooserSalidaMouseClicked
       //LocalDate salida = jDateChooserSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
      System.out.println("funca Mouse Clicked");
      /* System.out.print(jDateChooserSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
       Date salida= jDateChooserSalida.getDate();
       System.out.println(salida);
        String cadena=salida.toString();
        System.out.println(cadena);
        repaint();
        filtroPorFechaSalida();
        filtro = new TableRowSorter (jTableVuelos.getModel());
        jTableVuelos.setRowSorter(filtro);*/
  
    }//GEN-LAST:event_jDateChooserSalidaMouseClicked

    private void jDateChooserSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooserSalidaMouseEntered
        /*   System.out.println("funca Entered");
       System.out.print(jDateChooserSalida.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
       Date salida= jDateChooserSalida.getDate();
       System.out.println(salida);
        String cadena=salida.toString();
        System.out.println(cadena);
        repaint();
        filtroPorFechaSalida();
        filtro = new TableRowSorter (jTableVuelos.getModel());
        jTableVuelos.setRowSorter(filtro);*/
    }//GEN-LAST:event_jDateChooserSalidaMouseEntered

    private void limpiarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarVuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarVuelosActionPerformed

    private void limpiarVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarVuelosMouseClicked
       modelo.setRowCount(0); // TODO add your handling code here:
    }//GEN-LAST:event_limpiarVuelosMouseClicked

    private void jButtonVerAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerAsientosActionPerformed
       // ventana.setVisible(false);
       // Asientos.visibilidad(true);
      //panelContenedorAsientos.removeAll();
       panel.removeAll();
       panel1.removeAll();
       jButtonDisponible.setVisible(true);
       jButtonOcupado.setVisible(true);
       //jButtonVerAsientos.setEnabled(false);
       panelContenedorAsientos.setVisible(true);
       int fila = jTableVuelos.getSelectedRow();
       String id_aux = jTableVuelos.getValueAt(fila, 0).toString();
       int id= Integer.parseInt(id_aux);
      Vuelo vuelo = vD.buscarVuelo(id);
      AsientoData aD=new AsientoData();
   
       mostrarAsientos(aD.obtenerAsientosPorVuelo(vuelo));
       
       // panel.setVisible(true);  
       //panel1.setVisible(true);
           
       /*  int fila = jTableVuelos.getSelectedRow();
        String id_aux = jTableVuelos.getValueAt(fila, 0).toString();
        int id = Integer.parseInt(id_aux);
        Vuelo vuelo = new Vuelo();
        vuelo=vD.buscarVuelo(id);
        //System.out.println(vuelo);
        List<Asiento> listaAsientos= new ArrayList<>();
        listaAsientos=aD.obtenerAsientosPorVuelo(vuelo);
        
        for(int i=0;i<listaAsientos.size();i++){
        
        System.out.println (listaAsientos.get(i).getCodigoAsiento());
        }*/
      
      
        //Asientos ventanaAsientos= new Asientos(listaAsientos);
        //ventanaAsientos.setAsientos(listaAsientos);
        //ventanaAsientos.setVisible(true);
        //ventanaAsientos.mostrarAsientos();
       // Asientos.setAsientos(listaAsientos);
        //Asientos.visibilidad(true);
        
       
    }//GEN-LAST:event_jButtonVerAsientosActionPerformed

    private void jComboBoxOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOrigenActionPerformed

    private void jButtonDisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDisponibleActionPerformed

    private void jButtonOcupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcupadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOcupadoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Cliente cliente= new Cliente();
        ClienteData cD=new ClienteData();
        int dni=Integer.parseInt(nroDni.getText());
        cliente=cD.buscarClientePorDni(dni);

        if(cD.existe(cliente.getDni())){
            resultado.setText("Cliente Registrado");
            resultado.setForeground(Color.green);
            llenarCamposCliente(cliente);
        }else{vaciarCajasCliente();
            resultado.setForeground(Color.red);
            resultado.setText("no Registrado");}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nroPasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nroPasaporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nroPasaporteActionPerformed

    private void cerrarPanelDatosVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPanelDatosVueloActionPerformed
        jPanelDatosPasaje.setVisible(false);
    }//GEN-LAST:event_cerrarPanelDatosVueloActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
      panelContenedorAsientos.setVisible(false);
         //llenartabla
         
                
         
         //jPanelDatosPasaje.setVisible(false);
         jButtonDisponible.setVisible(false);
        jButtonOcupado.setVisible(false);
        
        
        ClienteData gestorCliente= new ClienteData();
        Cliente clienteNuevo= new Cliente();
        int dniNuevo=Integer.parseInt(nroDni.getText());
       System.out.println(dniNuevo);
        clienteNuevo.setDni(dniNuevo);
        clienteNuevo.setNombre(nombreCliente.getText());
        clienteNuevo.setApellido(apellidoCliente.getText());
        clienteNuevo.setPasaporte(Integer.parseInt(nroPasaporte.getText()));
        clienteNuevo.setTarjeta(Integer.parseInt(tarj1.getText()));
        clienteNuevo.setMail(email.getText());
        try {
            gestorCliente.altaCliente(clienteNuevo);
        } catch (SQLException ex) {
            Logger.getLogger(VistaNuevaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        nombreAerolinea1.setText(nombreAerolinea.getText());
        nombreAeronave1.setText(nombreAeronave.getText());
        nombreCiudadOrigen1.setText(nombreCiudadOrigen.getText());
        nombreCiudadDestino1.setText(nombreCiudadDestino.getText());
        fechaSalida1.setText(fechaSalida.getText());
        fechaArribo1.setText(fechaArribo.getText());
        ubicacionAsiento1.setText(ubicacionAsiento.getText());
        precioAsiento1.setText(precioAsiento.getText());
        
        
        
        
        panelDatosCliente.setVisible(true);
        dni.setText(nroDni.getText());
        pasaporte.setText(nroPasaporte.getText());
        nombre.setText(nombreCliente.getText());
        apellido.setText(apellidoCliente.getText());
        tarjeta.setText(tarj1.getText());
        mailCliente.setText(email.getText());
        
    }//GEN-LAST:event_siguienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      CompraData gestorCompra = new CompraData();
      Compra nuevaCompra= new Compra();
      Asiento asiento= new Asiento();
      AsientoData aD= new AsientoData();
      Cliente cliente=new Cliente();
      ClienteData cD=new ClienteData();
      cliente =cD.buscarClientePorDni(Integer.parseInt(dni.getText()));
      asiento=aD.buscarAsiento(Integer.parseInt(idAsientoComprado.getText()));
      nuevaCompra.setAsiento(asiento);
      asiento.setDisponible(false);
      aD.actualizarAsiento(asiento);
      nuevaCompra.setCliente(cliente);
      Timestamp horaActual = new Timestamp(System.currentTimeMillis());
      nuevaCompra.setFechaCompra(horaActual);
      nuevaCompra.setNroTarjeta(Integer.parseInt(tarjeta.getText()));
      try {
            int exito=gestorCompra.guardarCompra(nuevaCompra);
            if(exito==1){
            panelDatosCliente.setVisible(false);
            jPanelDatosPasaje.setVisible(false);
            panelContenedorAsientos.setVisible(false);
            jButtonDisponible.setVisible(false);
            jButtonOcupado.setVisible(false);
            JOptionPane.showMessageDialog(null,"Su Compra se realizado Exitosamente");
            vaciarCajasCliente();
            vaciarCajasDatosVuelo();
            panel.removeAll();
            panel1.removeAll();
            }else{
            }
        } catch (SQLException ex) {
            Logger.getLogger(VistaNuevaCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cerrarPanelConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarPanelConfirmarActionPerformed
       panelDatosCliente.setVisible(false);
    }//GEN-LAST:event_cerrarPanelConfirmarActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jDateChooserVueltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooserVueltaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserVueltaMouseClicked

    private void jDateChooserVueltaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooserVueltaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooserVueltaMouseEntered
     public void llenarDatosVuelo(int idAsiento){
        
     int fila = jTableVuelos.getSelectedRow();
        String id_aux = jTableVuelos.getValueAt(fila, 0).toString();
        int id= Integer.parseInt(id_aux);
        AsientoData aD= new AsientoData();
        Vuelo vuelo = vD.buscarVuelo(id);
        nombreAerolinea.setText(""+vuelo.getAerolinea());
        nombreAeronave.setText(""+vuelo.getTipoAeronave());
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yy HH:mm");
        fechaSalida.setText(""+formateador.format(vuelo.getFechaSalida()));
        fechaArribo.setText(""+formateador.format(vuelo.getFechaArribo()));
       Asiento asientoSeleccionado=   aD.buscarAsiento(idAsiento);
       
        idAsientoComprado.setText(""+idAsiento);
        idAsientoComprado.setName(""+idAsiento);
        
        ubicacionAsiento.setText(asientoSeleccionado.getCodigoAsiento());
        precioAsiento.setText(""+asientoSeleccionado.getPrecio());
        Ciudad origen = cD.getCiudad(vuelo.getCiudadOrigen().getIdCiudad());
        nombreCiudadOrigen.setText(""+origen.getNombre());
        Ciudad destino = cD.getCiudad(vuelo.getCiudadDestino().getIdCiudad());
        nombreCiudadDestino.setText(""+origen.getNombre());
    }
    
    
       public void llenarComboCiudades() {
        DefaultComboBoxModel modeloOrigen = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloDestino = new DefaultComboBoxModel();
        List<Ciudad> ciudades = cD.getCiudades();
        modeloOrigen.addElement("Seleccione ciudad de origen");
        jComboBoxOrigen.setModel(modeloOrigen);
        modeloDestino.addElement("Seleccione ciudad de destino");
        jComboBoxDestino.setModel(modeloDestino);
        for (int i = 0; i < ciudades.size(); i++) {
            modeloOrigen.addElement(ciudades.get(i).getNombre());
            jComboBoxOrigen.setModel(modeloOrigen);
            modeloDestino.addElement(ciudades.get(i).getNombre());
            jComboBoxDestino.setModel(modeloDestino);
        }
    }
    
    public void llenarTabla(List<Vuelo> vuelos) {
        if(vuelos.size()<=0){ 
        JOptionPane.showMessageDialog(null,"No se encontraron Vuelos");
        }
        else{ 
        modelo = (DefaultTableModel) jTableVuelos.getModel();
        modelo.setRowCount(0);
        Object[] fila = new Object[modelo.getColumnCount()];
        for (int i = 0 ; i < vuelos.size(); i++) {
            fila[0] = vuelos.get(i).getIdVuelo();
            fila[1] = vuelos.get(i).getAerolinea().toUpperCase();
            fila[2] = vuelos.get(i).getTipoAeronave().toUpperCase();
            Ciudad origen = cD.getCiudad(vuelos.get(i).getCiudadOrigen().getIdCiudad());
            fila[3] = origen.getNombre().toUpperCase();
            Ciudad destino = cD.getCiudad(vuelos.get(i).getCiudadDestino().getIdCiudad());
            fila[4] = destino.getNombre().toUpperCase();
            SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yy HH:mm");
            //System.out.println(formateador.format(vuelos.get(i).getFechaSalida()));
            fila[5] = formateador.format(vuelos.get(i).getFechaSalida());
            fila[6] = formateador.format(vuelos.get(i).getFechaArribo());
           
            modelo.addRow(fila);
        }       
    }
}
    
    public void llenarCampos() {
        int fila = jTableVuelos.getSelectedRow();
        String id_aux = jTableVuelos.getValueAt(fila, 0).toString();
        int id= Integer.parseInt(id_aux);
        
        Vuelo vuelo = vD.buscarVuelo(id);
        
        Ciudad origen = cD.getCiudad(vuelo.getCiudadOrigen().getIdCiudad());
        //nombreCiudadOrigen.setText(""+origen.getNombre());
        Ciudad destino = cD.getCiudad(vuelo.getCiudadDestino().getIdCiudad());
        //nombreCiudadDestino.setText(""+destino.getNombre());
        //jDateChooserSalida.setDate(Date.from(vuelo.getFechaSalida()));
        //jDateChooserArribo.setDate(Date.from(vuelo.getFechaArribo()));
      //Asiento asiento = aD.buscarAsientoPorVuelo(vuelo);
    }
    
 /*   private boolean camposVacios(){
        boolean hayVacias = false;
        if( nombreCiudadOrigen.getText().equals("") || nombreCiudadDestino.getText().equals("") ||
             jDateChooserVuelta.getDate() == null || jDateChooserVuelta.getDate() == null 
             ) {
            hayVacias = true;
        }
        return hayVacias;
    }
    */
    public static void visibilidad(boolean estado){
       ventana.setVisible(estado);
   }
      public void filtro(){
       // filtro.setRowFilter(RowFilter.regexFilter(nombreCiudadOrigen.getText().toUpperCase(),3));
    } 
      public void filtroCiudadDestino(){
       // filtro.setRowFilter(RowFilter.regexFilter(nombreCiudadDestino.getText().toUpperCase(),4));
    } 
      public void filtroPorFechaSalida(){
        filtro.setRowFilter(RowFilter.regexFilter(jDateChooserSalida.getDateFormatString(),5));
    } 
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaNuevaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JLabel apellido;
    private javax.swing.JTextField apellidoCliente;
    private javax.swing.JButton cerrarPanelConfirmar;
    private javax.swing.JButton cerrarPanelDatosVuelo;
    private javax.swing.JLabel dni;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fechaArribo;
    private javax.swing.JLabel fechaArribo1;
    private javax.swing.JLabel fechaSalida;
    private javax.swing.JLabel fechaSalida1;
    private javax.swing.JLabel idAsientoComprado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonDisponible;
    private javax.swing.JButton jButtonMostrarVuelos;
    private javax.swing.JButton jButtonOcupado;
    private javax.swing.JButton jButtonVerAsientos;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private com.toedter.calendar.JDateChooser jDateChooserSalida;
    private com.toedter.calendar.JDateChooser jDateChooserVuelta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelComprarAsiento;
    private javax.swing.JLabel jLabelCompras;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JLabel jLabelSalida;
    private javax.swing.JLabel jLabelVuelta;
    private javax.swing.JPanel jPanelDatosPasaje;
    private javax.swing.JPanel jPanelFondoSeleccion;
    private javax.swing.JScrollPane jScrollPaneVuelos;
    private javax.swing.JTable jTableVuelos;
    private javax.swing.JButton limpiarVuelos;
    private javax.swing.JLabel mailCliente;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombreAerolinea;
    private javax.swing.JLabel nombreAerolinea1;
    private javax.swing.JLabel nombreAeronave;
    private javax.swing.JLabel nombreAeronave1;
    private javax.swing.JLabel nombreCiudadDestino;
    private javax.swing.JLabel nombreCiudadDestino1;
    private javax.swing.JLabel nombreCiudadOrigen;
    private javax.swing.JLabel nombreCiudadOrigen1;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField nroDni;
    private javax.swing.JTextField nroPasaporte;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelContenedorAsientos;
    private javax.swing.JPanel panelDatosCliente;
    private javax.swing.JLabel pasaporte;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel precioAsiento;
    private javax.swing.JLabel precioAsiento1;
    private javax.swing.JLabel resultado;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField tarj1;
    private javax.swing.JLabel tarjeta;
    private javax.swing.JLabel ubicacionAsiento;
    private javax.swing.JLabel ubicacionAsiento1;
    // End of variables declaration//GEN-END:variables
}
