/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author asus pc
 */
public class VistaVueloAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaVueloAdmin
     */
    public VistaVueloAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelAdministrador = new javax.swing.JLabel();
        jLabelVuelos = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jTextFieldFiltrar = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();
        jScrollPaneVuelos = new javax.swing.JScrollPane();
        jTableVuelos = new javax.swing.JTable();
        jComboBoxAerolinea = new javax.swing.JComboBox<>();
        jComboBoxAeronave = new javax.swing.JComboBox<>();
        jComboBoxOrigen = new javax.swing.JComboBox<>();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        jDateChooserSalida = new com.toedter.calendar.JDateChooser();
        jDateChooserArribo = new com.toedter.calendar.JDateChooser();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jComboBoxAsiento = new javax.swing.JComboBox<>();
        jLabelAerolinea = new javax.swing.JLabel();
        jLabelAeronave = new javax.swing.JLabel();
        jLabelOrigen = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelSalida = new javax.swing.JLabel();
        jLabelArribo = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelAsiento = new javax.swing.JLabel();
        jPanelFondoSeleccion = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 204, 0));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        JPanel.setBackground(new java.awt.Color(153, 204, 51));
        JPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelInicio.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        jLabelInicio.setForeground(new java.awt.Color(102, 153, 51));
        jLabelInicio.setText("Inicio //");
        jLabelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInicio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JPanel.add(jLabelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 20, 98, 30));

        jLabelAdministrador.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabelAdministrador.setForeground(new java.awt.Color(102, 153, 51));
        jLabelAdministrador.setText("Administrador /");
        jLabelAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPanel.add(jLabelAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 20, -1, 30));

        jLabelVuelos.setBackground(new java.awt.Color(102, 153, 51));
        jLabelVuelos.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jLabelVuelos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVuelos.setText("Vuelos");
        JPanel.add(jLabelVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 30));

        jLabelCerrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(102, 153, 51));
        jLabelCerrar.setText("X");
        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        JPanel.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 15, 15));

        jTextFieldFiltrar.setToolTipText("");
        jTextFieldFiltrar.setBorder(null);
        jTextFieldFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldFiltrar.setSelectionColor(new java.awt.Color(102, 153, 51));
        JPanel.add(jTextFieldFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, 270, 31));

        jButtonFiltrar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonFiltrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.setToolTipText("");
        jButtonFiltrar.setBorder(null);
        jButtonFiltrar.setBorderPainted(false);
        jButtonFiltrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPanel.add(jButtonFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 75, 31));

        jTableVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idVuelo", "Aerolinea", "Aeronave", "Origen", "Destino", "Salida", "Arribo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableVuelos.setToolTipText("");
        jTableVuelos.setSelectionBackground(new java.awt.Color(102, 153, 51));
        jTableVuelos.getTableHeader().setReorderingAllowed(false);
        jScrollPaneVuelos.setViewportView(jTableVuelos);

        JPanel.add(jScrollPaneVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 111, 691, 239));

        jComboBoxAerolinea.setBackground(new java.awt.Color(153, 204, 51));
        jComboBoxAerolinea.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBoxAerolinea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccionar]", "Aerolineas Argentinas", "LATAM", "Emirates", "CopaAirlines", "AirFrance", "FlyBondi", "Qatar" }));
        jComboBoxAerolinea.setBorder(null);
        JPanel.add(jComboBoxAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 277, 30));

        jComboBoxAeronave.setBackground(new java.awt.Color(153, 204, 51));
        jComboBoxAeronave.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBoxAeronave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Seleccionar]", "Boeing 747", "Boeing 757", "Boeing 767", "Airbus A320", "Airbus A330", "Airbus A340" }));
        jComboBoxAeronave.setBorder(null);
        JPanel.add(jComboBoxAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 277, 30));

        jComboBoxOrigen.setBackground(new java.awt.Color(153, 204, 51));
        jComboBoxOrigen.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOrigen.setBorder(null);
        JPanel.add(jComboBoxOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 496, 277, 30));

        jComboBoxDestino.setBackground(new java.awt.Color(153, 204, 51));
        jComboBoxDestino.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDestino.setBorder(null);
        JPanel.add(jComboBoxDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 496, 277, 30));

        jDateChooserSalida.setBackground(new java.awt.Color(102, 153, 51));
        JPanel.add(jDateChooserSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 563, 128, 30));

        jDateChooserArribo.setBackground(new java.awt.Color(102, 153, 51));
        JPanel.add(jDateChooserArribo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 563, 128, 30));

        jComboBoxEstado.setBackground(new java.awt.Color(153, 204, 51));
        jComboBoxEstado.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEstado.setBorder(null);
        JPanel.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 563, 128, 30));

        jComboBoxAsiento.setBackground(new java.awt.Color(153, 204, 51));
        jComboBoxAsiento.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jComboBoxAsiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAsiento.setBorder(null);
        JPanel.add(jComboBoxAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 563, 128, 30));

        jLabelAerolinea.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelAerolinea.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAerolinea.setText("Aerolinea");
        JPanel.add(jLabelAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 405, -1, -1));

        jLabelAeronave.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelAeronave.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAeronave.setText("Aeronave");
        JPanel.add(jLabelAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 405, -1, -1));

        jLabelOrigen.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelOrigen.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrigen.setText("Ciudad de Origen");
        JPanel.add(jLabelOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        jLabelDestino.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDestino.setText("Ciudad de Destino");
        JPanel.add(jLabelDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jLabelSalida.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelSalida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSalida.setText("Salida");
        JPanel.add(jLabelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 538, -1, -1));

        jLabelArribo.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelArribo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelArribo.setText("Arribo");
        JPanel.add(jLabelArribo, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 538, -1, -1));

        jLabelEstado.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado.setText("Estado");
        JPanel.add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 538, -1, -1));

        jLabelAsiento.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabelAsiento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAsiento.setText("Asiento");
        JPanel.add(jLabelAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 538, -1, -1));

        jPanelFondoSeleccion.setBackground(new java.awt.Color(102, 153, 51));

        javax.swing.GroupLayout jPanelFondoSeleccionLayout = new javax.swing.GroupLayout(jPanelFondoSeleccion);
        jPanelFondoSeleccion.setLayout(jPanelFondoSeleccionLayout);
        jPanelFondoSeleccionLayout.setHorizontalGroup(
            jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanelFondoSeleccionLayout.setVerticalGroup(
            jPanelFondoSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        JPanel.add(jPanelFondoSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 380, 695, 255));

        jButtonEliminar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("- Eliminar vuelo");
        jButtonEliminar.setBorder(null);
        jButtonEliminar.setBorderPainted(false);
        jButtonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPanel.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 660, 159, 31));

        jButtonModificar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonModificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setText("/ Modificar vuelo");
        jButtonModificar.setBorder(null);
        jButtonModificar.setBorderPainted(false);
        jButtonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPanel.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 660, 159, 31));

        jButtonAgregar.setBackground(new java.awt.Color(102, 153, 51));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("+ Agregar vuelo");
        jButtonAgregar.setBorder(null);
        jButtonAgregar.setBorderPainted(false);
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPanel.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, 159, 31));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVueloAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVueloAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVueloAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVueloAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVueloAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxAerolinea;
    private javax.swing.JComboBox<String> jComboBoxAeronave;
    private javax.swing.JComboBox<String> jComboBoxAsiento;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxOrigen;
    private com.toedter.calendar.JDateChooser jDateChooserArribo;
    private com.toedter.calendar.JDateChooser jDateChooserSalida;
    private javax.swing.JLabel jLabelAdministrador;
    private javax.swing.JLabel jLabelAerolinea;
    private javax.swing.JLabel jLabelAeronave;
    private javax.swing.JLabel jLabelArribo;
    private javax.swing.JLabel jLabelAsiento;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelOrigen;
    private javax.swing.JLabel jLabelSalida;
    private javax.swing.JLabel jLabelVuelos;
    private javax.swing.JPanel jPanelFondoSeleccion;
    private javax.swing.JScrollPane jScrollPaneVuelos;
    private javax.swing.JTable jTableVuelos;
    private javax.swing.JTextField jTextFieldFiltrar;
    // End of variables declaration//GEN-END:variables
}
