/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reservadevuelos.vistas;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import reservadevuelos.modelo.Conexion;
import reservadevuelos.modelo.Vuelo;
import reservadevuelos.modelo.VueloData;

/**
 *
 * @author asus pc
 */
public class VentanaVuelo extends javax.swing.JFrame {

    // ATRIBUTOS
    private VueloData vueloData;
    private Conexion conexion;
    
    // CONSTRUCTOR
    public VentanaVuelo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTAerolinea = new javax.swing.JTextField();
        jTAeronave = new javax.swing.JTextField();
        jTOrigen = new javax.swing.JTextField();
        jTDestino = new javax.swing.JTextField();
        jTSalida = new javax.swing.JTextField();
        jTArribo = new javax.swing.JTextField();
        jTEstado = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTAerolinea.setText("Aerolinea");
        jTAerolinea.setToolTipText("");
        jTAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAerolineaActionPerformed(evt);
            }
        });

        jTAeronave.setText("Tipo de Aeronave");

        jTOrigen.setText("Ciudad de Origen");
        jTOrigen.setToolTipText("");

        jTDestino.setText("Ciudad de Destino");

        jTSalida.setText("Fecha de Salida");

        jTArribo.setText("Fecha de Arribo");

        jTEstado.setText("Estado");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTDestino)
                    .addComponent(jTSalida)
                    .addComponent(jTArribo)
                    .addComponent(jTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAerolinea)
                    .addComponent(jTAeronave)
                    .addComponent(jTOrigen)
                    .addComponent(jBGuardar))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTArribo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBGuardar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAerolineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAerolineaActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        if(!cajasVaciasVuelo()) {
            Vuelo nuevoVuelo = new Vuelo(jTAerolinea.getText(),
                                            jTAeronave.getText(),
                                            Integer.parseInt(jTOrigen.getText()), 
                                            Integer.parseInt(jTDestino.getText()),
                                            LocalDate.parse(jTSalida.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                                            LocalDate.parse(jTArribo.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                                            jTEstado.getText());
            vueloData.altaVuelo(nuevoVuelo);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private boolean cajasVaciasVuelo(){
        boolean hayvacias = false;
        if  (jTAerolinea.getText().equals("")
            || jTAeronave.getText().equals("")
            || jTOrigen.getText().equals("")
            || jTDestino.getText().equals("")
            || jTSalida.getText().equals("")
            || jTArribo.getText().equals("")
            || jTEstado.getText().equals("")){
            hayvacias=true;
        }
        return hayvacias;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JTextField jTAerolinea;
    private javax.swing.JTextField jTAeronave;
    private javax.swing.JTextField jTArribo;
    private javax.swing.JTextField jTDestino;
    private javax.swing.JTextField jTEstado;
    private javax.swing.JTextField jTOrigen;
    private javax.swing.JTextField jTSalida;
    // End of variables declaration//GEN-END:variables
}
